# Code Generated by ChatGPT from the prompt: "Write a Python implementation of the Crystals-Kyber
# key generation algorithm with comments."

import random


def generate_keypair(n, q):
    # Generate a secret key
    sk = [random.randint(0, q - 1) for _ in range(n)]

    # Generate a public key from the secret key
    pk = [random.randint(0, q - 1) for _ in range(n)]

    for i in range(n):
        pk[i] = (pk[i] - sk[i]) % q

    return sk, pk